export const defaultTypeEs = {
  'ghost': 'Fantasma',
  'dark': 'Siniestro',
  'electric': 'Eléctrico',
  'normal': 'Normal',
  'fire': 'Fuego',
  'psychic': 'Psíquico',
  'flying': 'Volador',
  'steel': 'Acero',
  'poison': 'veneno',
  'dragon': 'Dragón',
  'water': 'Agua',
  'ice': 'Hielo',
  'rock': 'Roca',
  'fighting': 'Lucha',
  'grass': 'planta',
  'bug': 'Bicho',
  'ground': 'Tierra',
  'fairy': 'Hada',
}